Finished the configuration file

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12,10 +12,15 @@ echo -e "Checking all the requirements...\n"
 all_reqs=true
 if ! command -v python3 &> /dev/null
 then
-	python2_version="$(python2 -V 2>&1)"
-	echo -e "${RED}ERROR: Python3 not found. \u2716${NC}\nLatest version of python is $python2_version\nPlease install python3\n"
-	all_reqs=false
-	unset python2_version
+	if ! command -v python2 &> /dev/null
+	then
+		echo -e "${RED}ERROR: No python installed. \u2716${NC}\\nPlease install Python3"
+	else
+		python2_version=$(python2 -V 2>&1)
+		echo -e "${RED}ERROR: Python3 not found. \u2716${NC}\nLatest version of python is $python2_version\nPlease install python3\n"
+		all_reqs=false
+		unset python2_version
+	fi
 else
 	echo -e "${GREEN}Found $(python3 --version) \u2714${NC}\n"
 fi
@@ -23,18 +28,50 @@ fi
 #pip3
 if ! command -v pip3 &> /dev/null
 then
-	pip_version="$(pip -V 2>&1)"
-	echo -e "${RED}ERROR: pip3 not found. \u2716${NC}\nLatest version of pip is $pip_version\nPlease install pip3\n"
+	echo -e "${RED}ERROR: pip3 not found. \u2716${NC}\n"
 	all_reqs=false
-	unset pip_version
 else
 	echo -e "${GREEN}Found $(pip3 --version) \u2714${NC}\n"
+fi
+
+#Nuitka
+if ! pip3 list | grep -F "Nuitka" &> /dev/null
+then
+	echo -e "${RED}ERROR: Python module Nuitka not found. \u2716${NC}\n"
+	all_reqs=false
+else
+	nuitka_version="$(pip3 list | grep -F "Nuitka")"
+	echo -e "${GREEN}Found $nuitka_version \u2714${NC}\n"
+	unset nuitka_version
 fi
 
 #Check that all of the requirements have been satisfied
 if ! $all_reqs
 then
 	echo -e "${RED}Some of the requirements have not been satisfied\nPlease install them and rerun this configuration script${NC}\n"
+	exit
 else
 	echo -e "${GREEN}All of the requriments are satisfied. Starting to build the binary files.${NC}\n"
 fi
+
+python3 -m nuitka --follow-imports lmp_auto.py 
+
+if ls | grep -qF "lmp_auto.bin"
+then
+	echo -e "${GREEN}The binary file has been successfully created.${NC}\n"
+	if echo $PATH | grep -qE '(:|^)/usr/local/bin:'
+	then
+		PATH=$PATH:/usr/local/bin
+	fi
+	cp lmp_auto.bin /usr/local/bin/lmp_auto
+else
+	echo -e "\n${RED}Something went wrong wile creating a binary file.${NC}\nPlease check for Nuitka errors.\n"
+fi
+
+
+
+
+
+
+
+
